# Generated by Django 5.1.1 on 2024-10-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(related_name='movies', to='firstapp.actor'),
        ),
    ]
