# Generated by Django 5.1.1 on 2024-10-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_alter_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watched',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
