# Generated by Django 5.0.2 on 2024-09-13 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='start_data',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
