# Generated by Django 5.0.2 on 2024-09-13 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_speciality_start_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='start_data',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
