# Generated by Django 5.0.2 on 2024-09-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_speciality_start_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
